projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - src/app/API.service.ts
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-west-3
        apiId: uddzylmtwjdtzoofmportubvsq
        frontend: javascript
        framework: angular
        amplifyJsLibraryVersion: 6
        maxDepth: 2
